

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver        #  驱动包
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root                 #用户名
    password: db@mysql

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰配置
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity,com.example.demo.bo
  configuration-properties: classpath:mybatis/mybatis-config.xml
server:
  port: 8777